name: Create Tag

on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        with:
          bump_version_scheme: minor